# ── Réseau ─────────────────────────────────────────────────────
spark.driver.bindAddress                        0.0.0.0
spark.network.timeout                           800s

# ── Ressources ─────────────────────────────────────────────────
spark.executor.instances                        2
spark.executor.cores                            1
spark.executor.memory                           1g
spark.driver.memory                             1g
spark.dynamicAllocation.enabled                 false

# ── SQL ────────────────────────────────────────────────────────
spark.sql.adaptive.enabled                      true
spark.serializer                                org.apache.spark.serializer.KryoSerializer

# ── ICEBERG : active les extensions SQL (MERGE INTO, etc.) ─────
spark.sql.extensions   org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions

# ── CATALOG "iceberg" : pointe vers Hive Metastore ────────────
# Toutes les tables seront référencées comme iceberg.bronze.xxx
spark.sql.catalog.iceberg                       org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.iceberg.type                  hive
spark.sql.catalog.iceberg.uri                   thrift://hive-metastore:9083
spark.sql.catalog.iceberg.io-impl               org.apache.iceberg.aws.s3.S3FileIO
spark.sql.catalog.iceberg.warehouse             s3a://iceberg/warehouse
spark.sql.catalog.iceberg.s3.endpoint          http://minio:9000
spark.sql.catalog.iceberg.s3.path-style-access true
spark.sql.catalog.iceberg.s3.access-key-id     minio
spark.sql.catalog.iceberg.s3.secret-access-key minio123
spark.sql.catalog.iceberg.s3.region            us-east-1

# ── S3A : accès MinIO ─────────────────────────────────────────
spark.hadoop.fs.s3a.impl                        org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.endpoint                    http://minio:9000
spark.hadoop.fs.s3a.path.style.access           true
spark.hadoop.fs.s3a.connection.ssl.enabled      false
spark.hadoop.fs.s3a.aws.credentials.provider    org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
spark.hadoop.fs.s3a.access.key                  minio
spark.hadoop.fs.s3a.secret.key                  minio123

# ── JVM options ───────────────────────────────────────────────
spark.driver.extraJavaOptions   -Daws.region=us-east-1 -Dcom.amazonaws.sdk.disableEc2Metadata=true
spark.executor.extraJavaOptions -Daws.region=us-east-1 -Dcom.amazonaws.sdk.disableEc2Metadata=true

# ── Variables pratiques ────────────────────────────────────────
spark.cdc.kafka.bootstrap                       kafka:9092
