databases:
  - database_name: Trino - CDC Lakehouse
    sqlalchemy_uri: trino://admin@trino:8080/iceberg
    expose_in_sqllab: true
    allow_run_async: true
    allow_ctas: true
    allow_cvas: true
    allow_dml: false
